# Generated by Django 5.0.6 on 2026-05-15 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('squat', 'Squat'), ('lunge', 'Lunge'), ('shoulder_raise', 'Shoulder Raise'), ('knee_extension', 'Knee Extension'), ('chest_expansion', 'Chest Expansion'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('rep_count', models.PositiveIntegerField(default=0)),
                ('overall_stability_score', models.FloatField(default=0.0, help_text='0.0–1.0; higher = smoother trajectory.')),
                ('quality_score', models.FloatField(default=0.0, help_text='0.0–1.0; clinician-facing aggregate of form quality.')),
                ('progress_trend', models.JSONField(blank=True, default=dict, help_text='Free-form summary metrics for trend charts on the dashboard, e.g. {"rom_avg": 0.82, "compensation_events": 3}.')),
                ('random_seed', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrajectoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_rate_hz', models.PositiveSmallIntegerField(default=15)),
                ('frame_count', models.PositiveIntegerField(default=0)),
                ('frames', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trajectory', to='clinical_sessions.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'started_at'], name='clinical_se_user_id_ac7c87_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['started_at'], name='clinical_se_started_533f59_idx'),
        ),
        migrations.AddIndex(
            model_name='trajectorydata',
            index=models.Index(fields=['session'], name='clinical_se_session_780f9b_idx'),
        ),
    ]
